name: Backend - Continuos Integration

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "reopened", "synchronize"]
    paths: ["packages/backend/**"]
  push:
    branches: ["main"]
    paths: ["packages/backend/**"]
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/backend

jobs:
  unitAndIntegrationTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16.x"
      - run: npm ci
      - name: Unit test
        run: npm test
      - name: Deploy test stack
        id: deploy-test-stack
        run: npm run deploy:test
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Integration test
        run: npm run test:integration
        env:
          APP_REGION: ${{ steps.deploy-test-stack.outputs.APP_REGION }}
          TABLE_NAME: ${{ steps.deploy-test-stack.outputs.TABLE_NAME }}
          LAMBDA_FUNCTION_NAME_PREFIX: ${{ steps.stack-deploy-test-stack.outputs.LAMBDA_FUNCTION_NAME_PREFIX }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
